services:
  # 1. O Banco de Dados
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=toolcare_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123 # Senha simples para o docker

  # 2. O Backend (Django)
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db # Aponta para o serviço acima
      - DB_NAME=toolcare_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_PORT=5432

  # 3. O Frontend (React)
  frontend:
    build: ./frontend/toolcare_ui
    volumes:
      - ./frontend/toolcare_ui:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # Necessário para Windows
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  postgres_data: